### ISSUE TITLE
N550JV device status enquiry

### ISSUE THREAD

**Issue by DAIGOR1024** [bakedpotato191/asusn550jv-hackintosh#3]
Hi, thanks for your great work! I also have a N550JV notebook and plan to install the Mac os on it.
I have a few questions as below:
1. which bios version are you using?
2. Which mac os version is installed on your N550JV?
3. Are the camera and the HDMI also working?
Thanks~

**Comment by superrnovae** [comment]
> Hi, thanks for your great work! I also have a N550JV notebook and plan to install the Mac os on it.
> 
> I have a few questions as below:
> 
> 1. which bios version are you using?
> 
> 2. Which mac os version is installed on your N550JV?
> 
> 3. Are the camera and the HDMI also working?
> 
> Thanks~

1. The latest available
2. macOS 11.5
3. Yes, they are.

**Comment by DAIGOR1024** [comment]
> > Hi, thanks for your great work! I also have a N550JV notebook and plan to install the Mac os on it.
> > I have a few questions as below:
> > 
> > 1. which bios version are you using?
> > 2. Which mac os version is installed on your N550JV?
> > 3. Are the camera and the HDMI also working?
> > 
> > Thanks~
> 
> 1. The latest available
> 2. macOS 11.5
> 3. Yes, they are.

Thanks~And does your notebook have touch screen?

**Comment by superrnovae** [comment]
> > > Hi, thanks for your great work! I also have a N550JV notebook and plan to install the Mac os on it.
> 
> > > I have a few questions as below:
> 
> > > 
> 
> > > 1. which bios version are you using?
> 
> > > 2. Which mac os version is installed on your N550JV?
> 
> > > 3. Are the camera and the HDMI also working?
> 
> > > 
> 
> > > Thanks~
> 
> > 
> 
> > 1. The latest available
> 
> > 2. macOS 11.5
> 
> > 3. Yes, they are.
> 
> 
> 
> Thanks~And does your notebook have touch screen?

It does not
